---
- name: Listen for events on a webhook
  hosts: web
  ## Define our source for events
  sources:
     - ansible.eda.url_check:
        urls:
          - http://webserver.ansible-automates.co.za
        delay: 10


  rules:
    ## Define the conditions we are looking for 
    - name: Web site is down
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: "Redeploy Webservices"
          organization: Default
          retries: 1
          delay: 10
    
  
