---
- name: Site Down
  hosts: webserver01.ansible-automates.co.za
  gather_facts: false
  become: true

  tasks:

    - debug:
        msg: "Website is down!"

    - name: Replace website
      copy:
       remote_src: yes
       src: /opt/index.html
       dest: /var/www/html/
       owner: apache
       group: apache
       mode: '0644'

    - name: Restart service
      service:
       name: "httpd"
       state: restarted
       enabled: yes
      register: restart
